Prepare release
ratt-ru/shadeMS pull request #112
Opened 2023-05-02 08:42 UTC by Athanaseus

2023-05-31 13:04 UTC, o-smirnov reviewed
LGTM

2023-06-01 13:48 UTC, sjperkins approved these changes

2023-06-01 13:49 UTC, sjperkins requested changes
Those glib warnings on the test cases look very odd. Do you know why they're occurring?

2023-06-02 10:00 UTC, Athanaseus commented
> Those glib warnings on the test cases look very odd. Do you know why they're occurring?

Not sure why that happened. I forced poetry installation instead of relying on the cache.
Perhaps I can also look into running the tests on a single `ubuntu-latest` platform going into the future?

2023-06-02 13:15 UTC, sjperkins approved these changes

2023-06-02 13:45 UTC, merged